### ISSUE TITLE
'TwoVarCompModelRotate' function need to be modified to output eigen vectors 

### ISSUE THREAD

**Issue by jinjinzhou** [OpenMendel/VarianceComponentModels.jl#1]
When using LRT for GWAS, eigen vectors of (co)variance matrices  needed to be stored under the null model so that we can rotate covariates including SNPs under all alternative models and to avoid to call  'TwoVarCompModelRotate' many times.

**Comment by Hua-Zhou** [comment]
It makes sense. Please go ahead make the changes.

**Comment by Hua-Zhou** [comment]
Fixed in fbfedc4f16e8fca84b66b2135ab99bf26245f427
