### ISSUE TITLE
mle_reml_ipynb fails when increasing dimension from 2 to 3

### ISSUE THREAD

**Issue by finmod** [OpenMendel/VarianceComponentModels.jl#11]
Trying to increase the dimension of the problem from 2 to 3 as follows: 

generate data from a d-variate response variance component model
using Random, LinearAlgebra
Random.seed!(123)
n = 1000   # no. observations
d = 3      # dimension of responses
m = 3      # no. variance components
p = 3      # no. covariates

X = randn(n, p)

Step 3 model fit:

vcmodel_mle = deepcopy(vcmodel)
@time logl, vcmodel_mle, Σse, Σcov, Bse, Bcov = fit_mle!(vcmodel_mle, vcdata; algo = :MM);

fails:

MethodError: no method matching TwoVarCompVariateRotate(::VarianceComponentVariate{Float64,3,Array{Float64,2},Array{Float64,2},Array{Float64,2}})
Closest candidates are:
  TwoVarCompVariateRotate(!Matched::Array{T<:VarianceComponentVariate,N} where N) where T<:VarianceComponentVariate at C:\Users\Denis\.julia\packages\VarianceComponentModels\6qDHu\src\VarianceComponentModels.jl:261
  TwoVarCompVariateRotate(!Matched::YT<:(Union{AbstractArray{T,2}, AbstractArray{T,1}} where T), !Matched::XT<:(Union{AbstractArray{T,2}, AbstractArray{T,1}} where T), !Matched::Array{T<:AbstractFloat,1}, !Matched::Array{T<:AbstractFloat,2}, !Matched::T<:AbstractFloat) where {T<:AbstractFloat, YT<:(Union{AbstractArray{T,2}, AbstractArray{T,1}} where T), XT<:(Union{AbstractArray{T,2}, AbstractArray{T,1}} where T)} at C:\Users\Denis\.julia\packages\VarianceComponentModels\6qDHu\src\VarianceComponentModels.jl:189
  TwoVarCompVariateRotate(!Matched::Union{AbstractArray{T,2}, AbstractArray{T,1}} where T, !Matched::Union{AbstractArray{T,2}, AbstractArray{T,1}} where T, !Matched::Array{T,1} where T, !Matched::Array{T,2} where T, !Matched::Real) at C:\Users\Denis\.julia\packages\VarianceComponentModels\6qDHu\src\VarianceComponentModels.jl:209
  ...

Stacktrace:
 [1] #fit_mle!#31(::Symbol, ::Function, ::VarianceComponentModel{Float64,3,Array{Float64,2},Array{Float64,2}}, ::VarianceComponentVariate{Float64,3,Array{Float64,2},Array{Float64,2},Array{Float64,2}}) at C:\Users\Denis\.julia\packages\VarianceComponentModels\6qDHu\src\two_variance_component.jl:1207
 [2] (::getfield(VarianceComponentModels, Symbol("#kw##fit_mle!")))(::NamedTuple{(:algo,),Tuple{Symbol}}, ::typeof(fit_mle!), ::VarianceComponentModel{Float64,3,Array{Float64,2},Array{Float64,2}}, ::VarianceComponentVariate{Float64,3,Array{Float64,2},Array{Float64,2},Array{Float64,2}}) at .\none:0
 [3] top-level scope at util.jl:156
 [4] top-level scope at In[10]:2

**Comment by Hua-Zhou** [comment]
Currently the package can only handle models with 2 variance
components (`m=2`). In you example, if you keep `m=2`, it should work.

If you'd like to contribute to the `m>2` case, this [paper](
https://arxiv.org/abs/1509.07426) is a good start point.

**Comment by finmod** [comment]
Correct. It does. Thank you for your instant reply.

I want to ask a follow up question but an "issue" here may not be the right place. Can the X*B part of the vcmodel be extended to a nonlinear model for instance lorenz63 as in here: https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/tutorials/ode_example.md ?

I find your mle_reml_ipynb just perfect for MLE estimation of systems as it also applies KL and Hua-Zhou methods just like no other (Newton, Fisher Information matrix etc.)  It also corresponds to Seber and Wild. There would just be some additional directions to push in terms of optimization algorithms including perhaps BlackBoxOptim.jl.

**Comment by Hua-Zhou** [comment]
The package as is cannot handle nonlinear model now. Current algorithm for MLE alternately updates mean component parameters and variance component parameters. We only need to call a nonlinear regression solver when updating the mean parameters. It should be something doable. 

I'm closing original thread.
