### ISSUE TITLE
Multiple variance components for univariate response

### ISSUE THREAD

**Issue by espenmei** [OpenMendel/VarianceComponentModels.jl#14]
Hi,

Is it possible to fit models where `Y` is a `n x 1` vector and `V` contains multiple covariance matrices? If not, would it be possible to add such functionality?

My application is that I want to model the data s a function several covariance matrices encoding both gentic and environmental similarity.

All the best,
Espen

**Comment by Hua-Zhou** [comment]
Multiple (>2) variance component models are not implemented in the package yet. We have some code for doing that, which we can share with you if you need it. @juhkim111

**Comment by espenmei** [comment]
Thanks for the kind offer. I currently found a way to solve this particular problem in Julia. Thanks for providing an excellent package!

**Comment by Hua-Zhou** [comment]
Glad it worked out for you @espenmei
