### ISSUE TITLE
Pkg.clone format listed requires public/private key

### ISSUE THREAD

**Issue by jcpapp** [OpenMendel/VarianceComponentModels.jl#2]
I think the format you list in your documentation under installation
Pkg.clone("git@github.com:OpenMendel/VarianceComponentModels.jl.git")
requires a public/private key set-up with github.

I think the alternate format
Pkg.clone("https://github.com/OpenMendel/VarianceComponentModels.jl.git")
would be better. It has the same basic functionality and can be run by anyone. Of course, since it does not require a public/private key, it is not as secure.

**Comment by Hua-Zhou** [comment]
It's fixed now. 
https://openmendel.github.io/VarianceComponentModels.jl/latest/#installation
Thanks, @jcpapp !
