### ISSUE TITLE
Variance component estimation for mixed model with 2 loci

### ISSUE THREAD

**Issue by fboehm** [OpenMendel/VarianceComponentModels.jl#4]
Hi, Does VarianceComponentModels.jl, as it currently exists, permit the user to specify a model like:

vec(Y) ~ N(XB, Sigma)

where Y is a n by 2 matrix of (bivariate) phenotypes (and vec(Y) is a 2n-length vector), X is a known 2n by 2p matrix, B is a 2p-long vector, and Sigma is a  2n by 2n covariance matrix? I'm assuming that the covariance matrix Sigma = Sigma1 \otimes V1 + Sigma2 \otimes V2, where

Sigma1 & Sigma2 are known n by n matrices and V1 and V2 are unknown 2 by 2 matrices. I'd like to estimate V1, V2, and B.

If this isn't currently implemented, can you provide any suggestions as to how I might build on your existing code to implement it? 

Much thanks!

**Comment by Hua-Zhou** [comment]
@fboehm, there is a chance you can just feed the transpose of your data into functions and read off the estimates. 

In your model, `Y` is `n x d`, `X` is `nd x pd`, `B` is `pd x 1`, `Sigma1, Sigma2` are `n x n`, and `V1`, `V2` are `d x d`. You assume 
`vec(Y) ~ N(XB, Sigma1 \otimes V1 + \Sigma2 \otimes V2)`. 
Let `Kdn` be the `nd x nd` commutation matrix
<https://en.wikipedia.org/wiki/Commutation_matrix>
Then
`vec(Y') = Knd vec(Y) ~ N(Knd X B, Knd (Sigma1 \otimes V1 + Sigma2 \otimes V2) Knd') = N(Knd X B, V1 \otimes Sigma1 + V2 \otimes Sigma2)`.

So feeding the transformed data `Y'`, `Knd X`, `Sigma1`, `Sigma2` into functions, you may read off the  estimates of `V1`, `V2` directly. The catch is current functions assume the mean structure `vec(XB)`. Is there any structure in your `X` matrix? Or if the primary interest is estimating `V1`, `V2`, you can use REML: first obtain residuals from ordinary least squares then fit the variance component model using just residuals. If none of these apply, it's also straightforward modify current functions to accommodate your `X`.

**Comment by fboehm** [comment]
Thanks, @Hua-Zhou! Your explanation is very helpful. I think that I can proceed based on your detailed reply. Thanks again!
