### ISSUE TITLE
Julia version 1.0.1 support

### ISSUE THREAD

**Issue by nhavt** [OpenMendel/VarianceComponentModels.jl#6]
Hi all, 
As far as I know, the current package can't be used in Julia 1.0.1. However, I am wondering whether you might upgrade the package for Julia 1.0.1 soon. Could you please let me know about it? Thanks in advance!

**Comment by Hua-Zhou** [comment]
Yes, we're planning to upgrade the package for Julia 1.0. I expect to have
it done within 1-2 weeks.

**Comment by Hua-Zhou** [comment]
The package supports v0.7 and later since release v0.1.0.
